// ── Phase 04: Configure ─────────────────────────────────────────────────────

import { type InstallContext, REPO_URL, REPO_BRANCH, TIER_MAP } from '../lib/config.ts';
import { exec } from '../lib/shell.ts';
import { mergeEnv } from '../lib/env.ts';
import { IS_WINDOWS, IS_MACOS, copyDir, removeDir, getComposeFileSeparator, getPermissionFixHint } from '../lib/platform.ts';
import * as ui from '../lib/ui.ts';
import { Spinner } from '../lib/ui.ts';
import { existsSync, mkdirSync, copyFileSync, readdirSync, readFileSync, chmodSync } from 'node:fs';
import { join, basename, relative } from 'node:path';
import { tmpdir, cpus as osCpus } from 'node:os';
import { execFileSync } from 'node:child_process';
import { IS_LINUX } from '../lib/platform.ts';

// ── Cryptographic helpers (shared across phases) ────────────────────────────

/** Generate a random hex string of the given byte length. */
export function randHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return Array.from(buf, (b) => b.toString(16).padStart(2, '0')).join('');
}

/** Generate a random base64 string of the given byte length. */
export function randBase64(bytes: number): string {
  const buf = new Uint8Array(bytes);
  crypto.getRandomValues(buf);
  return Buffer.from(buf).toString('base64');
}

export async function configure(ctx: InstallContext): Promise<void> {
  ui.phase(4, 6, 'Configure', '~30s');

  // Clone or update repository
  if (existsSync(join(ctx.installDir, '.env'))) {
    ui.info('Existing installation found — updating in place');
    await gitPull(ctx);
  } else {
    await cloneRepo(ctx);
  }

  // Generate external LLM overlay if using Ollama or external backend.
  // This overlay disables the built-in llama-server container since inference
  // is handled by an external service (Ollama on host, user-provided API, etc.)
  if (ctx.llmBackend === 'ollama' || ctx.llmBackend === 'external') {
    const overlayPath = join(ctx.installDir, 'docker-compose.external-llm.yml');
    if (!existsSync(overlayPath)) {
      const { writeFileSync } = await import('node:fs');
      writeFileSync(overlayPath, [
        '# External LLM Backend Overlay — auto-generated by dream-installer',
        '# Disables the built-in llama-server container when using Ollama or external API',
        '',
        'services:',
        '  llama-server:',
        '    profiles: [disabled]',
        '',
      ].join('\n'));
    }
  }

  // Resolve compose overlays
  const composeFiles = resolveComposeFiles(ctx);
  const relPaths = composeFiles.map((f) => relative(ctx.installDir, f));
  const extCount = relPaths.filter((p) => p.startsWith('extensions/')).length;
  ui.ok(`Configured ${composeFiles.length} compose files (${extCount} extensions)`);
  for (const p of relPaths) ui.debug(`  compose: ${p}`);

  // Generate .env (or merge on re-install)
  await generateEnv(ctx, composeFiles);

  // Create data directories with correct ownership
  await setupDataDirs(ctx);

  // Generate service-specific configs
  await generateSearXNGConfig(ctx);
  await generateOpenClawConfig(ctx);
}

async function cloneRepo(ctx: InstallContext): Promise<void> {
  if (ctx.dryRun) {
    ui.info('[DRY RUN] Would clone repository');
    return;
  }

  const spinner = new ui.Spinner('Cloning repository...');
  spinner.start();

  try {
    const tmpCloneDir = join(tmpdir(), `dream-clone-${Date.now()}`);
    await exec(['git', 'clone', '--depth', '1', '--branch', REPO_BRANCH, REPO_URL, tmpCloneDir], { timeout: 120_000 });

    const srcDir = join(tmpCloneDir, 'dream-server');
    if (!existsSync(srcDir)) {
      spinner.fail('dream-server directory not found in repository');
      process.exit(1);
    }

    // Copy dream-server contents to install dir
    mkdirSync(ctx.installDir, { recursive: true });
    copyDir(srcDir, ctx.installDir);
    removeDir(tmpCloneDir);

    spinner.succeed(`Cloned to ${ctx.installDir}`);
  } catch (e) {
    spinner.fail('Clone failed');
    throw e;
  }
}

async function gitPull(ctx: InstallContext): Promise<void> {
  if (ctx.dryRun) {
    ui.info('[DRY RUN] Would pull latest changes');
    return;
  }

  try {
    await exec(['git', 'pull', '--ff-only'], { cwd: ctx.installDir, timeout: 30_000 });
    ui.ok('Updated to latest version');
  } catch {
    ui.warn('Could not auto-update — continuing with existing version');
  }
}

export function resolveComposeFiles(ctx: InstallContext): string[] {
  const dir = ctx.installDir;
  const files: string[] = [];

  // Base compose file
  const base = join(dir, 'docker-compose.base.yml');
  const standalone = join(dir, 'docker-compose.yml');

  if (existsSync(base)) {
    files.push(base);
  } else if (existsSync(standalone)) {
    files.push(standalone);
  }

  // GPU-specific overlay
  if (ctx.gpu.backend === 'nvidia') {
    const nvidia = join(dir, 'docker-compose.nvidia.yml');
    if (existsSync(nvidia)) files.push(nvidia);
  } else if (ctx.gpu.backend === 'amd') {
    const amd = join(dir, 'docker-compose.amd.yml');
    if (existsSync(amd)) files.push(amd);
  } else if (ctx.gpu.backend === 'apple') {
    // macOS: try installers/macos/docker-compose.macos.yml (canonical path)
    const macosOverlay = join(dir, 'installers', 'macos', 'docker-compose.macos.yml');
    const appleFallback = join(dir, 'docker-compose.apple.yml');
    if (existsSync(macosOverlay)) files.push(macosOverlay);
    else if (existsSync(appleFallback)) files.push(appleFallback);
  }

  // vLLM overlay — replaces llama-server with vLLM container
  if (ctx.llmBackend === 'vllm') {
    const vllm = join(dir, 'docker-compose.vllm.yml');
    if (existsSync(vllm)) files.push(vllm);
  }

  // External LLM overlay — disables built-in llama-server container
  // Used when Ollama or another external inference server is managing models
  if (ctx.llmBackend === 'ollama' || ctx.llmBackend === 'external') {
    const externalLlm = join(dir, 'docker-compose.external-llm.yml');
    if (existsSync(externalLlm)) files.push(externalLlm);
  }

  // Extension service compose files (sorted for deterministic ordering)
  const extDir = join(dir, 'extensions', 'services');
  if (existsSync(extDir)) {
    for (const svc of readdirSync(extDir).sort()) {
      const composeFile = join(extDir, svc, 'compose.yaml');
      if (existsSync(composeFile)) {
        // Check if the service is enabled
        if (shouldEnableExtension(svc, ctx)) {
          files.push(composeFile);

          // Some extensions (e.g. ComfyUI) use GPU-specific overlays that
          // contain the actual service definition.  The base compose.yaml may
          // be an empty stub — without the overlay no container is created.
          const gpuOverlayMap: Record<string, string> = {
            nvidia: `compose.nvidia.yaml`,
            amd:    `compose.amd.yaml`,
            apple:  `compose.apple.yaml`,
          };
          const overlayName = gpuOverlayMap[ctx.gpu.backend];
          if (overlayName) {
            const gpuOverlay = join(extDir, svc, overlayName);
            if (existsSync(gpuOverlay)) {
              files.push(gpuOverlay);
            }
          }
        }
      }
    }
  }

  // User compose override support (docker-compose.override.yml)
  const overrideFile = join(dir, 'docker-compose.override.yml');
  if (existsSync(overrideFile)) files.push(overrideFile);

  return files;
}

function shouldEnableExtension(name: string, ctx: InstallContext): boolean {
  // Map extension directory names to feature flags
  const featureMap: Record<string, keyof typeof ctx.features> = {
    'n8n': 'workflows',
    'openclaw': 'openclaw',
    'whisper': 'voice',
    'tts': 'voice',
    'qdrant': 'rag',
    'embeddings': 'rag',
    'comfyui': 'imageGen',
    'perplexica': 'webSearch',
    'searxng': 'webSearch',
    'litellm': 'litellm',
  };

  const feature = featureMap[name];
  if (feature) return ctx.features[feature];

  // Extensions without a feature flag are always enabled
  // (privacy-shield, token-spy — lightweight security/monitoring)
  return true;
}

/**
 * Resolve the LLM API URL based on the selected backend.
 * - llamacpp: Docker service llama-server on port 8080 (internal)
 * - vllm: Same Docker service, overridden by vLLM overlay
 * - ollama: External Ollama on host (port 11434)
 * - external: User-provided URL
 * - apple: macOS host via Docker gateway (port 8080)
 */
function resolveLlmApiUrl(ctx: InstallContext): string {
  switch (ctx.llmBackend) {
    case 'ollama':
      return ctx.externalLlmUrl || 'http://host.docker.internal:11434';
    case 'external':
      return ctx.externalLlmUrl || 'http://host.docker.internal:8080';
    case 'vllm':
    case 'llamacpp':
    default:
      // Apple Silicon uses host.docker.internal because llama-server runs natively
      if (ctx.gpu.backend === 'apple') return 'http://host.docker.internal:8080';
      return 'http://llama-server:8080';
  }
}

async function generateEnv(ctx: InstallContext, composeFiles: string[]): Promise<void> {
  const envPath = join(ctx.installDir, '.env');
  const isReinstall = existsSync(envPath) && !ctx.force;

  if (ctx.dryRun) {
    ui.info('[DRY RUN] Would generate .env');
    return;
  }

  const tierConfig = TIER_MAP[ctx.tier];

  const generatedLines = [
    `# Dream Server Configuration — ${tierConfig?.name || 'Custom'} Edition`,
    `# Generated by dream-installer on ${new Date().toISOString()}`,
    `# Tier: ${ctx.tier} (${tierConfig?.name || 'Custom'})`,
    ``,
    `# ── Mode & Backend ───────────────────────────────────────────`,
    `DREAM_MODE=local`,
    `LLM_API_URL=${resolveLlmApiUrl(ctx)}`,
    `GPU_BACKEND=${ctx.gpu.backend}`,
    ``,
    `# ── Cloud API Keys ───────────────────────────────────────────`,
    `ANTHROPIC_API_KEY=`,
    `OPENAI_API_KEY=`,
    `TOGETHER_API_KEY=`,
    ``,
    `# ── Model Configuration ──────────────────────────────────────`,
    `LLM_MODEL=${tierConfig?.model || 'qwen3-8b'}`,
    `GGUF_FILE=${tierConfig?.ggufFile || 'Qwen3-8B-Q4_K_M.gguf'}`,
    `CTX_SIZE=${tierConfig?.context || 16384}`,
    `MAX_CONTEXT=${tierConfig?.context || 16384}`,
    ``,
  ];

  // AMD-specific GPU variables (container device access + ROCm tuning)
  if (ctx.gpu.backend === 'amd') {
    let videoGid = '44';
    let renderGid = '992';
    if (IS_LINUX) {
      try {
        const videoResult = execFileSync('getent', ['group', 'video'], { encoding: 'utf-8', timeout: 2000 });
        const vid = videoResult.trim().split(':')[2];
        if (vid) videoGid = vid;
      } catch { /* use default */ }
      try {
        const renderResult = execFileSync('getent', ['group', 'render'], { encoding: 'utf-8', timeout: 2000 });
        const rid = renderResult.trim().split(':')[2];
        if (rid) renderGid = rid;
      } catch { /* use default */ }
    }
    generatedLines.push(
      `# ── GPU Group IDs (for container device access) ──────────────`,
      `VIDEO_GID=${videoGid}`,
      `RENDER_GID=${renderGid}`,
      ``,
      `# ── AMD ROCm Settings ────────────────────────────────────────`,
      `HSA_OVERRIDE_GFX_VERSION=11.5.1`,
      `ROCBLAS_USE_HIPBLASLT=0`,
      ``,
    );
  }

  generatedLines.push(
    `# ── Ports ────────────────────────────────────────────────────`,
    `LLAMA_SERVER_PORT=8080`,
    `WEBUI_PORT=3000`,
    `DASHBOARD_PORT=3001`,
    `WHISPER_PORT=9000`,
    `TTS_PORT=8880`,
    `N8N_PORT=5678`,
    `QDRANT_PORT=6333`,
    `QDRANT_GRPC_PORT=6334`,
    `LITELLM_PORT=4000`,
    `OPENCLAW_PORT=7860`,
    `SEARXNG_PORT=8888`,
    `OLLAMA_PORT=11434`,
    `OPENCODE_PORT=3003`,
    ``,
    `# ── Security (auto-generated, keep secret!) ──────────────────`,
    `WEBUI_SECRET=${randHex(32)}`,
    `DASHBOARD_API_KEY=${randHex(32)}`,
    `N8N_USER=admin`,
    `N8N_PASS=${randBase64(16)}`,
    `LITELLM_KEY=sk-dream-${randHex(16)}`,
    `OPENCLAW_TOKEN=${randHex(24)}`,
    `OPENCODE_SERVER_PASSWORD=${randBase64(16)}`,
    `DIFY_SECRET_KEY=${randHex(32)}`,
    ``,
    `# ── LiveKit (WebRTC voice) ────────────────────────────────────`,
    `LIVEKIT_API_KEY=devkey-${randHex(8)}`,
    `LIVEKIT_API_SECRET=${randBase64(32)}`,
    ``,
    `# ── Voice Settings ───────────────────────────────────────────`,
    `WHISPER_MODEL=base`,
    `TTS_VOICE=en_US-lessac-medium`,
    ``,
    `# ── Web UI Settings ──────────────────────────────────────────`,
    `WEBUI_AUTH=true`,
    `ENABLE_WEB_SEARCH=true`,
    `WEB_SEARCH_ENGINE=searxng`,
    ``,
    `# ── n8n Settings ─────────────────────────────────────────────`,
    `N8N_AUTH=true`,
    `N8N_HOST=localhost`,
    `N8N_WEBHOOK_URL=http://localhost:5678`,
    ``,
    `# ── Compose Stack ────────────────────────────────────────────`,
    `COMPOSE_FILE=${composeFiles.map((f) => relative(ctx.installDir, f)).join(getComposeFileSeparator())}`,
    ``,
    `# ── Features ─────────────────────────────────────────────────`,
    `ENABLE_VOICE=${ctx.features.voice}`,
    `ENABLE_WORKFLOWS=${ctx.features.workflows}`,
    `ENABLE_RAG=${ctx.features.rag}`,
    `ENABLE_OPENCLAW=${ctx.features.openclaw}`,
    `ENABLE_IMAGE_GEN=${ctx.features.imageGen}`,
    `ENABLE_WEB_SEARCH_STACK=${ctx.features.webSearch}`,
    `ENABLE_LITELLM=${ctx.features.litellm}`,
    ``,
    `# ── LLM Backend ──────────────────────────────────────────────`,
    `LLM_BACKEND=${ctx.llmBackend}`,
    ``,
    `# ── System ───────────────────────────────────────────────────`,
    `TIMEZONE=${Intl.DateTimeFormat().resolvedOptions().timeZone}`,
    `ENABLE_DEVTOOLS=${ctx.features.devtools}`,
    ``,
    `# ── Resource Limits ──────────────────────────────────────────`,
    `LLAMA_CPU_LIMIT=${Math.max(1, osCpus().length).toFixed(1)}`,
  );

  // Add vLLM-specific env vars
  if (ctx.llmBackend === 'vllm' && tierConfig) {
    const vllmArgs = tierConfig.vllmArgs.join(' ');
    generatedLines.push(
      `VLLM_MODEL=${tierConfig.vllmModel}`,
      `VLLM_ARGS=${vllmArgs}`,
      `VLLM_HF_CACHE=./data/hf-cache`,
      `VLLM_IMAGE=vllm/vllm-openai:v0.17.0`,
    );
  }

  const generatedEnv = generatedLines.join('\n');

  if (isReinstall) {
    // Merge: preserve user-edited values, add any new keys
    const existing = readFileSync(envPath, 'utf-8');
    const merged = mergeEnv(existing, generatedEnv);
    await Bun.write(envPath, merged);
    ui.ok('.env merged (user edits preserved, new keys added)');
  } else {
    await Bun.write(envPath, generatedEnv + '\n');
    ui.ok('Generated .env with secure random secrets');
  }

  // Secure the secrets file (chmod 600) — skip on Windows
  if (!IS_WINDOWS) {
    try {
      chmodSync(envPath, 0o600);
    } catch {
      ui.warn('.env permissions could not be set — fix manually: chmod 600 .env');
    }
  }
}

/**
 * Create data directories with correct ownership (UID 1000:1000).
 *
 * Many containers run as non-root (node user, UID 1000) but Docker creates
 * bind-mount directories as root when they don't exist, causing EACCES errors.
 * This creates them preemptively with the right ownership.
 */
async function setupDataDirs(ctx: InstallContext): Promise<void> {
  if (ctx.dryRun) {
    ui.info('[DRY RUN] Would create data directories');
    return;
  }

  // All data dirs that containers write to, mapped from compose volume mounts
  const dataDirs = [
    'data/models',
    'data/open-webui',
    'data/n8n',
    'data/openclaw',
    'data/openclaw/home',
    'data/qdrant',
    'data/searxng',
    'data/token-spy',
    ...(ctx.llmBackend === 'vllm' ? ['data/hf-cache'] : []),
    // ComfyUI bind-mount dirs — Docker creates them as root if missing,
    // causing permission denied for the container (runs as UID 1000)
    ...(ctx.features.imageGen ? [
      'data/comfyui/models',
      'data/comfyui/output',
      'data/comfyui/input',
      'data/comfyui/workflows',
    ] : []),
  ];

  let created = 0;
  for (const dir of dataDirs) {
    const fullPath = join(ctx.installDir, dir);
    if (!existsSync(fullPath)) {
      mkdirSync(fullPath, { recursive: true });
      created++;
    }
  }

  // Fix ownership — containers run as UID 1000 (node user)
  // Skip on Windows — Docker Desktop handles bind mount permissions
  if (IS_WINDOWS || IS_MACOS) {
    // Windows: Docker Desktop handles bind mount permissions
    // macOS: standard UID is 501, not 1000. Docker Desktop VirtioFS handles permissions.
    if (created > 0) {
      ui.ok(`Created ${created} data directories`);
    }
  } else if (process.getuid?.() === 0) {
    try {
      await exec(
        ['chown', '-R', '1000:1000', join(ctx.installDir, 'data')],
        { throwOnError: false, timeout: 10000 },
      );
      if (created > 0) {
        ui.ok(`Created ${created} data directories (owned by UID 1000)`);
      }
    } catch {
      ui.warn('Could not set data directory ownership — some services may fail');
      ui.info(getPermissionFixHint(join(ctx.installDir, 'data')));
    }
  } else {
    if (created > 0) {
      ui.ok(`Created ${created} data directories`);
      ui.warn('Run with sudo to set correct ownership, or fix with:');
      ui.info(getPermissionFixHint(join(ctx.installDir, 'data')));
    }
  }
}

/**
 * Generate SearXNG settings.yml with randomized secret key.
 */
async function generateSearXNGConfig(ctx: InstallContext): Promise<void> {
  const configPath = join(ctx.installDir, 'data', 'searxng', 'settings.yml');
  if (existsSync(configPath)) return;
  if (ctx.dryRun) {
    ui.info('[DRY RUN] Would generate SearXNG config');
    return;
  }

  // Uses module-level randHex() from top of file

  const settings = `# SearXNG settings — generated by dream-installer
use_default_settings: true

general:
  instance_name: "Dream Search"

server:
  secret_key: "${randHex(32)}"
  bind_address: "127.0.0.1"
  port: 8888

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en"

ui:
  static_use_hash: true
  default_theme: simple
`;

  mkdirSync(join(ctx.installDir, 'data', 'searxng'), { recursive: true });
  await Bun.write(configPath, settings);
  ui.ok('Generated SearXNG config (settings.yml)');
}

/**
 * Generate OpenClaw config with model and provider settings.
 */
async function generateOpenClawConfig(ctx: InstallContext): Promise<void> {
  if (!ctx.features.openclaw) return;

  const configPath = join(ctx.installDir, 'data', 'openclaw', 'openclaw.json');
  if (existsSync(configPath)) return;
  if (ctx.dryRun) {
    ui.info('[DRY RUN] Would generate OpenClaw config');
    return;
  }

  const tierConfig = TIER_MAP[ctx.tier];
  const model = tierConfig?.model || 'qwen3-8b';

  const config = {
    model,
    provider: 'openai_compatible',
    api_base: `http://${ctx.gpu.backend === 'apple' ? 'host.docker.internal' : 'llama-server'}:8080/v1`,
    max_tokens: tierConfig?.context || 16384,
    temperature: 0.7,
  };

  mkdirSync(join(ctx.installDir, 'data', 'openclaw'), { recursive: true });
  await Bun.write(configPath, JSON.stringify(config, null, 2) + '\n');
  ui.ok('Generated OpenClaw config (openclaw.json)');
}
